"""empty message

Revision ID: 0b6ac656e43e
Revises: 
Create Date: 2019-11-12 11:10:42.658823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b6ac656e43e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Spider_Warehouse')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Spider_Warehouse',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Spider_Warehouse_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('html', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('blog_name', sa.VARCHAR(length=160), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=280), autoincrement=False, nullable=True),
    sa.Column('line', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('insert_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('other_info', sa.VARCHAR(length=170), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Spider_Warehouse_pkey')
    )
    # ### end Alembic commands ###
