"""empty message

Revision ID: 21179934caf6
Revises: 6bb4254bfc25
Create Date: 2019-11-07 16:04:10.115738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21179934caf6'
down_revision = '6bb4254bfc25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_log', sa.Column('user_agent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_log', 'user_agent')
    # ### end Alembic commands ###
