"""empty message

Revision ID: 6bb4254bfc25
Revises: 9fb35a4713e2
Create Date: 2019-11-07 15:41:26.019360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6bb4254bfc25'
down_revision = '9fb35a4713e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route', sa.String(length=20), nullable=True),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.Column('ip_address', sa.String(length=20), nullable=True),
    sa.Column('cookie', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Spider_Warehouse')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Spider_Warehouse',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Spider_Warehouse_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('html', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('blog_name', sa.VARCHAR(length=160), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=280), autoincrement=False, nullable=True),
    sa.Column('line', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('insert_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('other_info', sa.VARCHAR(length=170), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Spider_Warehouse_pkey')
    )
    op.drop_table('access_log')
    # ### end Alembic commands ###
