"""empty message

Revision ID: 9fb35a4713e2
Revises: ecb14fc4f8de
Create Date: 2019-10-31 23:04:30.061816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fb35a4713e2'
down_revision = 'ecb14fc4f8de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Spider_Warehouse')
    op.drop_table('pynews_back')
    op.create_unique_constraint(None, 'pynews', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pynews', type_='unique')
    op.create_table('pynews_back',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tags', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('read_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pub_time', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=180), autoincrement=False, nullable=True),
    sa.Column('other_info', sa.VARCHAR(length=170), autoincrement=False, nullable=True),
    sa.Column('blog_name', sa.VARCHAR(length=160), autoincrement=False, nullable=True),
    sa.Column('line', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('preview', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.SMALLINT(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pynews_pkey'),
    sa.UniqueConstraint('title', name='pynews_title_key')
    )
    op.create_table('Spider_Warehouse',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Spider_Warehouse_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('html', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('blog_name', sa.VARCHAR(length=160), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=180), autoincrement=False, nullable=True),
    sa.Column('line', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('insert_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('other_info', sa.VARCHAR(length=170), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Spider_Warehouse_pkey')
    )
    # ### end Alembic commands ###
