# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: My_blog_CI_CD

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image-name: [my_blog]
        image-version: [1.0]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

#    - name: Test with pytest
#      run: |
#        pytest

    - name: docker build and push TCCLOUD
      env:
        aliyun_username: ${{ secrets.TCCLOUD_USERNAME }}
        aliyun_password: ${{ secrets.TCLOUD_PASSWORD }}
      run: |
        sudo docker login --username=${{ secrets.TCCLOUD_USERNAME }} ccr.ccs.tencentyun.com --password=${{ secrets.TCLOUD_PASSWORD }}
        sudo docker build -t ${{ matrix.image-name }}:${{ matrix.image-version }} .
        sudo docker tag ${{ matrix.image-name }}:${{ matrix.image-version }} cccr.ccs.tencentyun.com/private_use/blog:${{ matrix.image-version }}
        sudo docker push cccr.ccs.tencentyun.com/private_use/blog:${{ matrix.image-version }}